parameters:
    ramsey.uuid.provider.node.system_node_provider.class: Ramsey\Uuid\Provider\Node\SystemNodeProvider
    akeneo_batch_queue.hydrator_job_execution_message_hydrator.class: Akeneo\Bundle\BatchQueueBundle\Hydrator\JobExecutionMessageHydrator
    akeneo_batch_queue.queue.database_job_execution_queue_factory.class: Akeneo\Bundle\BatchQueueBundle\Queue\DatabaseJobExecutionQueueFactory
    akeneo_batch_queue.queue.job_execution_message_repository.class: Akeneo\Bundle\BatchQueueBundle\Queue\JobExecutionMessageRepository

services:
    ramsey.uuid.provider.node.system_node_provider:
        class: '%ramsey.uuid.provider.node.system_node_provider.class%'

    akeneo_batch_queue.hydrator_job_execution_message_hydrator:
        class: '%akeneo_batch_queue.hydrator_job_execution_message_hydrator.class%'
        arguments:
            - '@doctrine.orm.entity_manager'

    akeneo_batch_queue.queue.job_execution_message_repository:
        class: '%akeneo_batch_queue.queue.job_execution_message_repository.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@akeneo_batch_queue.hydrator_job_execution_message_hydrator'

    akeneo_batch_queue.queue.database_job_execution_queue_factory:
        class: '%akeneo_batch_queue.queue.database_job_execution_queue_factory.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@akeneo_batch_queue.queue.job_execution_message_repository'
